### ISSUE TITLE
Push v1.0.1 to Terraform Registry

### ISSUE THREAD

**Issue by sgrissom-rxss** [aws-ia/terraform-aws-eks-blueprints-addon#12]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

[`v1.0.1`](https://github.com/aws-ia/terraform-aws-eks-blueprints-addon/releases/tag/v1.0.1) is released (thanks for the quick turnaround!). Can this be pushed to the [Terraform Registry](https://registry.terraform.io/modules/aws-ia/eks-blueprints-addon) now?

**Comment by bryantbiggs** [comment]
hmm, that should have been automatic. let me check into that, apologies

**Comment by bryantbiggs** [comment]
ok v1.0.1 is now synced up to the registry - thanks for letting us know!
