### ISSUE TITLE
empty policy tying to be created using module example

### ISSUE THREAD

**Issue by shaked-develeap** [aws-ia/terraform-aws-eks-blueprints-addon#16]
## Description
Hi Team!
first of all let me thanks you for this module, I see great potential and usage in this module, though im getting an error that looks like a bug:
Trying the example in main to create a IRSA Only.
I get an error on policy format, looks like its because the module if configured to use policy_document, even if I havnt given one, Id expect logic to differentiate and (perhaps) concat a the data from a given policy arn and additional policy_document.

I would love to hear your opinion and if i missed something on my side.

## Versions

- Module version [Required]:
"~ 1.1" and "~ 1.0"

- Terraform version:
Terraform v1.5.0
- Provider version(s):
"~> 5.8"

```hcl
module "eks" {
  source  = "terraform-aws-modules/eks/aws"
  version = "~> 19.13"
  cluster_name    = (local.name_prefix != "" || local.name_prefix != null) ? "${local.name_prefix}eks" : "eks"
  cluster_version = "1.27"
  create_cloudwatch_log_group = false
  # EKS Addons
  cluster_addons = {
    vpc-cni    = {}
    coredns    = {}
    kube-proxy = {}
    aws-ebs-csi-driver = {}
  }

  vpc_id                          = module.vpc[0].vpc_id
  subnet_ids                      = module.vpc[0].private_subnets
  cluster_endpoint_public_access  = false
  cluster_endpoint_private_access = true
  eks_managed_node_groups = {
    test_initial = {
      instance_types = var.eks_instance_types
      min_size       = 1
      max_size       = 2
      desired_size   = 2
      key_name       = aws_key_pair.key_pair.id
      network_interfaces = [{ associate_public_ip_address = false }] # required
      iam_role_additional_policies = {
        AmazonSSMManagedInstanceCore = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
        AmazonEKSWorkerNodePolicy    = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
        AmazonEKS_CNI_Policy         = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
      }
    }
  }
}

# https://aws-ia.github.io/terraform-aws-eks-blueprints-addons/main/
module "eks_blueprints_addon" {
  source = "aws-ia/eks-blueprints-addon/aws"
  version = "~> 1.1"

  # Disable helm release
  create_release = false
  # IAM role for service account (IRSA)
  create_role = true
  role_name   = "aws-vpc-cni-ipv4"
  role_policies = {
    AmazonEKS_CNI_Policy = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
  }
  oidc_providers = {
    this = {
      provider_arn    = module.eks.oidc_provider_arn
      namespace       = var.eks_irsas[count.index].namespace
      service_account = var.eks_irsas[count.index].service_account
    }
  }
}
```

## Expected behavior
I think creation of a policy should be dependent on aws_iam_policy_document if no documents are given, no reason to replicate the policy (unless create_policy is set to true), and at least concat the given policy data + documents (if given)

### Terminal Output Screenshot(s)

![Screenshot 2023-07-19 at 15 29 29](https://github.com/aws-ia/terraform-aws-eks-blueprints-addon/assets/77541750/e67f7cf9-20e4-4999-bfb1-c49c89610021)

![Screenshot 2023-07-19 at 17 00 17](https://github.com/aws-ia/terraform-aws-eks-blueprints-addon/assets/77541750/61301dff-8fc7-4ac7-82de-b5de8bbe5aa3)

**Comment by shaked-develeap** [comment]
Thanks for the reply, @bryantbiggs 
IMO it makes no sense for the module to give me that error, adding more logic to the creation of a policy seems in order.
In my case Im creating multiple IRSAs some from an existing policy, some from a `aws_iam_policy_document` (as in the example), more over that if trying the example fails, so one of: the example or the backend module needs to be fixed ..

**Comment by shaked-develeap** [comment]
this is my current solution, seems counter intuitive to need to do so, so I wont get the empty policy error:

`create_policy = length(try(coalesce(var.eks_irsas[count.index].source_policy_documents, var.eks_irsas[count.index].override_policy_documents), [])) != 0 ? true : false`

**Comment by bryantbiggs** [comment]
the module is designed to support creating custom addons with IRSA integration where the majority of use cases require a custom IAM policy. So it is designed from the perspective of the majority use case, which means additional configuration may be required for edge cases. 

In terms of this:
>   create_policy = length(try(coalesce(var.eks_irsas[count.index].source_policy_documents, var.eks_irsas[count.index].override_policy_documents), [])) > 0 ? true : false # <--- Added

Thats outside the scope of the module. We cannot design or pre-empt the various ways that users could re-wrap the module. The module is designed from a standard Terraform module perspective (I suspect this is a Terraform workspaces issue but won't go down that rabbit hole)

**Comment by shaked-develeap** [comment]
too bad.
I dont think this is an edge case, More over I think Modules should not require the user to customize input in order not to receive an unreasonable error.
If you dont agree with the above at least this: the example given in `main.tf` does not work
