### ISSUE TITLE
support specifying multiple IAM roles

### ISSUE THREAD

**Issue by joaocc** [aws-ia/terraform-aws-eks-blueprints-addon#23]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?
Being able to use this module to install helm charts that create several SAs, and that recommend more than one IAM role to be created, due to security or functional requirements.

#### Describe the solution you would like
In addition to being able to specify a list of SAs, be able to specify a list of IAM roles, and a mapping between both.

#### Describe alternatives you have considered
Not using the module

#### Additional context
This came up in the context of https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/26.
The helm chart for flux2 creates 6 service accounts, and the documentation recommends creating 2 IAM roles to be assigned to 3 of the SAs.
This deployment doesn't seem possible using `terraform-aws-eks-blueprints-addon`.

Please note that I understand that the module seems to have been able to address the needs of many of the addons in v5. However, I would assume this need would be needed for secure deployment on more complex environments. However I didn't check all other addons (v4 or v5) so I may be missing something.

**Comment by bryantbiggs** [comment]
closing this for now - I don't think this is the appropriate avenue to try to attach multiple roles since the module is designed to be a 1:1 of helm chart and IAM role
