### ISSUE TITLE
Return Helm Chart Configurations

### ISSUE THREAD

**Issue by williamsbobby1423** [aws-ia/terraform-aws-eks-blueprints-addon#24]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I have a pull request that handles this issue. 

#### What is the outcome that you are trying to reach?
The outcome of this change would enable an additional module to manage a gitops process using components created by this module.

When the helm release is not enabled, we lose IRSA information that should be passed to the helm chart and that information can be used by a downstream module that such as a module that handles gitops.

#### Describe the solution you would like

return the helm configurations that would be used for the helm chart as an output

#### Additional context

I am raising this issue because I have a module that manages deployments via a GitOp that supports both argocd and fluxcd. Information from this module such as IRSA and helm chart configuration information is passed to the GitOps module to allow either ArgoCD or FluxCD the ability to manage the deployments of addons. I will also put a link to those modules that enable gitops processes. Maybe that module can be adopted by blueprints, if that's of interest, here is a link to the repos: 

GitOPS Module: https://github.com/williamsbobby1423/terraform-aws-eks-blueprints-gitops/tree/v3-alpha
Enable FluxCD: https://github.com/williamsbobby1423/terraform-aws-eks-blueprints-addons/tree/feature-fluxcd

**Comment by bryantbiggs** [comment]
Thank you! However, this module is not related to GitOps or a GitOps approach so closing this out
