### ISSUE TITLE
policy generated by allow_self_assume_role triggers "Overly permissive trust policy" alert in AWS

### ISSUE THREAD

**Issue by joaocc** [aws-ia/terraform-aws-eks-blueprints-addon#25]
## Description
The current code for `allow_self_assume_role` generates a policy that causes AWS console to generate a warning.
> Overly permissive trust policy exists in your trust relationships
Broad access: Principals that include a wildcard (*, ?) can be overly permissive.

While this warning it factually correct (there is indeed a "*"), it seems not to be a real issue due to the condition. My knowledge of AWS policies doesn't run so deep, so I would ask someone else to double check this.

However this is an annoying warning, triggering a lot of red flags on security monitoring software. 
From the documentation examples (https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/) it would seem this could be rewritten to achieve the same goal without triggering the alerts.

Below is a proposal but, as mentioned above, this is illustrative, and needs to be checked.
```
  dynamic "statement" {
    # https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/
    for_each = var.allow_self_assume_role ? [1] : []

    content {
      sid     = "ExplicitSelfRoleAssumption"
      effect  = "Allow"
      actions = ["sts:AssumeRole"]

      principals {
        type        = "AWS"
        identifiers = ["arn:${local.partition}:iam::${local.account_id}:role${var.role_path}${local.role_name_condition}"]
      }
    }
  }
```

## Versions

- Module version [Required]: 1.1.1

**Comment by bryantbiggs** [comment]
Are you enabling the self assume permissions?

**Comment by joaocc** [comment]
Yes. In cert-manager (https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/269) and others. This is why i came across these warnings/alerts.

**Comment by bryantbiggs** [comment]
thank you but this is not something we are looking to change in the project at this time - the policy statement is set behind a conditional which defaults to `false`; meaning that the permissions do not exist until a user opts into those permissions.

**Comment by joaocc** [comment]
Well, if the user enables the policy, then it opens the role to *everyone* in AWS (even from other AWS accounts). 
I would say this is not a good practice, as per AWS warning when this is created and documentation.

If you prefer not to restrict to a role (as exemplified before) then, at least, I would urge you to reconsider the possibility to restrict the source AWS Account via something like `"arn:${local.partition}:iam::${local.account_id}:*"`.
As it is, is too easy for someone to expose their role to be assumed by anyone else.

Thanks

**Comment by bryantbiggs** [comment]
That is not true - it is restricted per the AWS documentation 

https://github.com/aws-ia/terraform-aws-eks-blueprints-addon/blob/327207ad17f3069fdd0a76c14d3e07936eff4582/main.tf#L124-L128

**Comment by joaocc** [comment]
Oh, I see. You are correct. 
I didn't notice the condition block :S Sorry for jumping to the previous conclusion.
In that case it's more the annoyance of having AWS console raising the alerts everytime and having to overwrite.
Thanks for the prompt response.
