### ISSUE TITLE
Feature request: Ability to create Service Account

### ISSUE THREAD

**Issue by Almenon** [aws-ia/terraform-aws-eks-blueprints-addon#26]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Easily and accurately create a service account

#### Describe the solution you would like

A way to create a service account via this module

#### Describe alternatives you have considered

Creating a service account manually via a helm chart. This is easy to do, but it's also easy to make a typo. Alternatively, setup a system from sending information from this module to be automatically consumed by the helm repository. This is accurate, but it requires you to make both a terraform change and a helm change.

Creating a service account via this module would be both easy and accurate.

#### Additional context

Usually helm charts create the service account for you. In this case we are using spark to create the pods, so there is no helm chart to create the service account for us. We would have to make one ourself.

If the idea is approved I might submit a PR for this.

**Comment by bryantbiggs** [comment]
I think this is something best left to users to implement since the scenario you described will be specific to each users environment. For the addons themselves, the recommendation is to use Helm to manage that for you

**Comment by Almenon** [comment]
This would be nice to have for anyone who runs Spark on Kubernetes, it's not specific to us. But you can close this issue if you wish.
