### ISSUE TITLE
why are some bool variables default value set to null?

### ISSUE THREAD

**Issue by rgl** [aws-ia/terraform-aws-eks-blueprints-addon#27]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

Why are some `bool` variables default value set to `null`? Also, their documentation mentions the default is a specific value, e.g., `Defaults to false`.

For example, the `wait_for_jobs` variable is declared as, https://github.com/aws-ia/terraform-aws-eks-blueprints-addon/blob/v1.1.1/variables.tf#L197-L201:

```hcl
variable "wait_for_jobs" {
  description = "If wait is enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as `timeout`. Defaults to `false`"
  type        = bool
  default     = null
}
```

**Comment by bryantbiggs** [comment]
Descriptions typically come from the resource https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#wait_for_jobs

Setting the default to `null` just means that this module doesn't have an opinion on the default value and therefore its whatever set in the provider or the upstream API

**Comment by rgl** [comment]
interesting. are theses descriptions automatically updated when the upstream is updated? if not, can't these descriptions induce the user in error when the upstream changes the default?

**Comment by bryantbiggs** [comment]
Is there an issue that you are running into?

**Comment by rgl** [comment]
No issue at all. I'm just intrigued why is it like that. As it didn't match my expectations. I'm even surprised that null is accepted. Which reveals that I have to read more about this.

**Comment by bryantbiggs** [comment]
its a very common practice, one that we use across all of our modules in https://github.com/terraform-aws-modules

**Comment by rgl** [comment]
oh its explained at https://developer.hashicorp.com/terraform/language/expressions/types#null. when using a wrapper module to wrap other modules/resources the use of `null` kinda makes some sense. still, having a wrapper module variable with a description with "Default: false", but it actually uses `null`, is still odd to me. Please feel free to close this issue if that's ok.

**Comment by bryantbiggs** [comment]
The description is there to make users aware of what value they will get if they don't choose one. If you have multiple layers of abstractions, you would have to dig through those to find out what value will be set 

Closing this out for now, but feel free to reach out with any further questions!
