### ISSUE TITLE
lifecycle options

### ISSUE THREAD

**Issue by cdenneen** [aws-ia/terraform-aws-eks-blueprints-addon#29]
Currently `lifecycle` isn't an option on a module:
```
╷
│ Error: Reserved block type name in module block
│
│   on modules/eks_addons/cilium.tf line 46, in module "cilium":
│   46:   lifecycle {
│
│ The block type name "lifecycle" is reserved for use by Terraform in a
│ future version.
```
so need some way to add `lifecycle` to the underlying `helm_release` here.

Right now plan after importing existing helm_release to be managed here shows changes to `metadata` being completely removed as well as adding things like `create_namespace`, `repository` and `values`. 

Is there a way to pass these down as `ignore_changes` to the `helmrelease.this[0]` resource?

**Comment by bryantbiggs** [comment]
You cannot use variables in lifecycle blocks [1]:

> The lifecycle settings all affect how Terraform constructs and traverses the dependency graph. As a result, only literal values can be used because the processing happens too early for arbitrary expression evaluation.

https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#literal-values-only
